version: "3.9"

services:
  frontend:
    build: ./client
    restart: always
    command: expo start -c
    stdin_open: true
    environment: 
      REACT_NATIVE_PACKAGER_HOSTNAME: ${IP}
      EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    env_file: .env
    networks:
      - rdp-app
    volumes:
      - ./client/:/usr/src/app/client/
  db:
    image: kartoza/postgis
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54322:5432"
    networks:
      - rdp-app
    volumes:
      - postgis-data:/var/lib/postgresql
  backend:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - rdp-app
    depends_on:
      - db
    env_file: .env
networks:
  rdp-app:
    driver: bridge
volumes:
  postgis-data: