# Generated by Django 3.1.7 on 2021-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210419_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='closingHour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='openingHour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')]),
        ),
    ]
