# Generated by Django 3.1.7 on 2021-05-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210501_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
    ]
