# Generated by Django 3.1.7 on 2021-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_dish_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='description',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.URLField(default='https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/vimdb/202685_0-803-5447-5447.jpg'),
            preserve_default=False,
        ),
    ]
