# Generated by Django 3.1.7 on 2021-05-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210419_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='OpeningHour',
        ),
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together={('weekday', 'restaurant')},
        ),
    ]
