# Generated by Django 3.1.7 on 2021-06-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210606_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryManData',
        ),
    ]
