# Generated by Django 3.1.7 on 2021-06-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_restaurantowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantOwner',
        ),
    ]
