# Generated by Django 3.1.7 on 2021-06-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_restaurantowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.ManyToManyField(to='api.CuisineType'),
        ),
    ]
