# Generated by Django 3.1.7 on 2021-06-06 17:18

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210606_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryManData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Online'), (2, 'Delivering'), (3, 'Offline')], default=3)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('last_online', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
