FROM python:3

ENV PYTHONUNBUFFERED=1
ENV CHOKIDAR_USEPOLLING=true

WORKDIR /usr/src/back

COPY requirements.txt /usr/src/back

RUN apt-get update &&\
    apt-get install -y binutils libproj-dev gdal-bin libgdal-dev
RUN apt-get install -y python3-gdal
RUN pip install -r requirements.txt

COPY . /usr/src/back